### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by quark67** [AZE38/2DToyJanusGravity#1]
If have clicked on Initialize and on Run Simulation with Safari and Firefox on Mac.

Result: only a green circle and no animation.

**Comment by AZE38** [comment]
browser - Chrome : ok - Microsft Edge : ok - Brave : ok

but other without chromium base have errors at the moment.

**Comment by quark67** [comment]
Thanks. I have also tested with an outdated version of Brave on Mac, but with a recent version, it works.

**Comment by quark67** [comment]
Update: it works also on recent versions of the Safari browser. All to do for it to working is enabling WebGPU, which is experimental on WebKit, the engine under Safari. To do so, you need to go to Settings of Safari, Advanced tab, enable Show features for web developers, and then go in Feature Flags tab, and enable WebGPU (cf. https://webkit.org/demos/webgpu/, which also suggest to not browse the entire web with this setting enabled. By the way, the examples shown on this WebKit page are currently working in Safari Technology Preview, but not in Safari version 17.4.1). 

**in Advanced:**
![image](https://github.com/AZE38/2DToyJanusGravity/assets/9338576/ad6e3739-3d06-48f2-940f-be7228e45e20)

**in Feature Flags:**
![image](https://github.com/AZE38/2DToyJanusGravity/assets/9338576/67da42d4-70e6-4e92-97a9-0c4d27d1b5ba)

Perhaps you can update the README file with some of the above informations, so Safari users can easily toy with your simulator without changing the browser.
